# Generated by Django 4.2.5 on 2023-09-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
