# Generated by Django 4.2.5 on 2023-09-10 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_sermon_testimony_alter_user_post_musicfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfavorite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
